adding upgrade code

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -95,3 +95,35 @@ jobs:
       run: |
             helm upgrade $RELEASE_NAME apache-airflow/airflow -f ./values.yaml --set defaultAirflowTag=2.7.3rc1
       if: success()
+
+    - name: verify upgraded airflow installed
+      run: |
+        kubectl get pods
+        kubectl get services
+        POD_NAME=($(kubectl get pods | grep -E 'worker' | awk '{print $1}'))
+        echo "Pod Name: $POD_NAME"
+        kubectl exec -it  $POD_NAME -- airflow version
+        sleep 180s 
+        kubectl exec -it  $POD_NAME -- airflow dags list
+        kubectl exec -it  $POD_NAME -- airflow dags unpause init_dag
+        kubectl exec -it  $POD_NAME -- airflow dags trigger init_dag -o json
+        output=$(kubectl exec -it  $POD_NAME -- airflow dags trigger init_dag -o json | awk 'NR==2')  
+        echo "output is : $output"
+        execution_date=$(echo "$output" | jq -r '.[0].logical_date')
+        echo "execution_date: $execution_date"
+        # Add a loop to check the DAG state until it becomes 'success' or 'failed'
+        kubectl exec -it $POD_NAME -- airflow dags state init_dag $execution_date
+        while true; do
+          state=$(kubectl exec -it $POD_NAME -- airflow dags state init_dag $execution_date |  awk '{print $1}')
+          if [ "$state" == "success" ]; then
+            echo "DAG state is $state."
+            exit 0
+          elif [ "$state" == "failed" ]; then
+             echo "DAG state is $state."
+            exit 1
+          else
+            echo "DAG state is $state. Waiting for it to become 'success' or 'failed..."
+            sleep 5  # You can adjust the sleep interval as needed
+          fi
+        done
+      if: success()
