updating gh action

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -61,8 +61,25 @@ jobs:
           POD_NAME=($(kubectl get pods | grep -E 'worker' | awk '{print $1}'))
           echo "Pod Name: $POD_NAME"
           kubectl exec -it  $POD_NAME -- airflow version
-          sleep 180s 
-          kubectl exec -it  $POD_NAME -- airflow dags list
+          kubectl exec -it  $POD_NAME airflow dags unpause init_dag
+          run_id =$(date -u +'%Y-%m-%dT%H:%M:%S+00:00')
+          kubectl exec -it  $POD_NAME airflow dags trigger init_dag $run_id
+          # Add a loop to check the DAG state until it becomes 'success' or 'failed'
+          while true; do
+            state=$(kubectl exec -it $POD_NAME airflow dags state init_dag $run_id)
+            if [ "$state" == "success" ] || [ "$state" == "failed" ]; then
+              echo "DAG state is $state."
+              exit 1
+            else
+              echo "DAG state is $state. Waiting for it to become 'success' or 'failed..."
+              sleep 5  # You can adjust the sleep interval as needed
+            fi
+          done
+      
+          
+          
+          
+        
 
       if: success()
 
